//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik.Modul.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountDay
    {
        public int Id { get; set; }
        public Nullable<int> SummaryId { get; set; }
        public Nullable<System.DateTime> TodayDate { get; set; }
        public string Name { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> TotalCount { get; set; }
    
        public virtual Summary Summary { get; set; }
    }
}
