//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik.Modul.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Summary()
        {
            this.CountDay = new HashSet<CountDay>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountDay> CountDay { get; set; }
    }
}
